name: tokenized-strategy-ape-mix

plugins:
  - name: solidity
  - name: etherscan
  - name: foundry
  - name: infura
  - name: alchemy
  - name: vyper

default_ecosystem: ethereum

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.9.5

  - name: tokenized-strategy
    github: yearn/tokenized-strategy
    ref: v3.0.2
    contracts_folder: src
    exclude: 
     - test/**/*

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.9.5"
    - "@tokenized-strategy=tokenized-strategy/v3.0.2"

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: foundry

foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura